#!/bin/bash

git fetch && \
npm run build && \
git checkout -b deploy origin/gh-pages && \
git ls-files | xargs rm -f && \
cp -R public/* . && \
rm -r public && \
git add . && \
git commit -m deploy && \
git push origin deploy:gh-pages && \
git checkout - && \
git branch -D deploy
