/* AUTOGENERATED. DO NOT MODIFY. */
/* eslint-disable */
import React from 'react';
import Clipboard from 'App/components/icons/Clipboard';
import Logout from 'App/components/icons/Logout';
import StarOutline from 'App/components/icons/StarOutline';
import Star from 'App/components/icons/Star';
import Trashcan from 'App/components/icons/Trashcan';

const icons = {
  'clipboard': Clipboard,
  'logout': Logout,
  'star-outline': StarOutline,
  'star': Star,
  'trashcan': Trashcan,
};

type Props = {
  icon: keyof typeof icons;
  size?: number;
};

function Icon(props: Props) {
  const IconComponent = icons[props.icon];
  const size = props.size || 13;
  const style = {
    fill: 'currentcolor',
    height: size,
    width: size,
  };
  return (
    <IconComponent preserveAspectRatio="xMidYMid meet" style={style} />
  );
}

export default Icon;
  